spring:
  jpa:
    hibernate:
        ddl-auto: validate

    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB



  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 1234
    url: jdbc:postgresql://localhost:5432/SwapBookDB
  sql:
    init:
      platform: postgres



